remote_theme: pmarsceill/just-the-docs
logo: "/assets/images/logo.png"
og_image: "/assets/images/facebook.png"
header:
  og_image: "/assets/images/facebook.png"
defaults:
  - scope:
      path: ""
    values:
      image: "/assets/images/facebook.png"
aux_links:
  "Home":
    - "//ssyooo.github.io/covid19content/"
  "Help Us":
    - "//www.usdigitalresponse.org/"
  "GitHub":
    - "//github.com/ssyooo/covid19content"
footer_content: "This is a free, open source resource created by volunteers with U.S. Digital Response. Contact us at info@usdigitalresponse.org if you have questions or feedback."
ga_tracking: UA-163579596-1

